// ── Paliers ───────────────────────────────────────────────────────────────
// Contenu (données) des paliers du jeu — extrait de types/game.ts pour séparer
// la table de contenu des définitions de types.
export interface PalierConfig {
  id: number; name: string; universe: string; arc: string; subtitle: string;
  bgGradient: string; accentColor: string; bossTimerSeconds: number; monstersPerPalier: number;
}

export const PALIERS: PalierConfig[] = [
  { id:1,  name:'ARC SAIYEN',        universe:'Dragon Ball Z',                arc:'Arc Saiyen',                  subtitle:'Les Saiyens débarquent sur Terre',      bgGradient:'linear-gradient(180deg,#0a0f1a,#070b14)', accentColor:'#f97316', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:2,  name:'EAST BLUE',         universe:'One Piece',                    arc:'Saga East Blue',              subtitle:'La mer des rêves commence ici',          bgGradient:'linear-gradient(180deg,#041424,#030d1a)', accentColor:'#3b82f6', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:3,  name:'EXAMEN CHŪNIN',     universe:'Naruto',                       arc:'Première Partie',             subtitle:'Le ninja des feuilles grandit',          bgGradient:'linear-gradient(180deg,#0a1a08,#061004)', accentColor:'#f97316', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:4,  name:'KANTO',             universe:'Pokémon',                      arc:'Région Kanto',                subtitle:'Attrapez-les tous !',                   bgGradient:'linear-gradient(180deg,#0f0a1a,#08061a)', accentColor:'#f59e0b', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:5,  name:'PALAIS COGNITIF',   universe:'Persona 5',                    arc:'Les Voleurs Fantômes',        subtitle:'Tu vas nous le rendre',                 bgGradient:'linear-gradient(180deg,#1a0000,#0d0000)', accentColor:'#ef4444', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:6,  name:'USINE PLAYTIME',    universe:'Poppy Playtime',               arc:'Chapitre 3',                  subtitle:'Ils veulent juste jouer',               bgGradient:'linear-gradient(180deg,#001a1a,#000d0d)', accentColor:'#22d3ee', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:7,  name:'CLOVER KINGDOM',    universe:'Black Clover',                 arc:'Saga des Rois Maléfiques',    subtitle:'La magie est tout',                     bgGradient:'linear-gradient(180deg,#0a1a00,#060d00)', accentColor:'#4ade80', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:8,  name:'ZONE DANGER',       universe:'Brotato',                      arc:'Vague après vague',           subtitle:'Survive ou meurs',                      bgGradient:'linear-gradient(180deg,#1a0a00,#0d0600)', accentColor:'#fb923c', bossTimerSeconds:90,   monstersPerPalier:10 },
  { id:9,  name:'TEMPEST',           universe:'Tensei Slime',                 arc:'Nation de Tempest',           subtitle:'Rimuru veut la paix',                   bgGradient:'linear-gradient(180deg,#001a1a,#000d12)', accentColor:'#34d399', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:10, name:'OVERWORLD',         universe:'Minecraft',                    arc:'Minecraft Overworld',         subtitle:'La nuit tombe...',                      bgGradient:'linear-gradient(180deg,#0a0a00,#050500)', accentColor:'#86efac', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:11, name:'GRANDE BARRIÈRE',   universe:'Subnautica',                   arc:'Les Profondeurs',             subtitle:'4546B — Ne pas descendre',              bgGradient:'linear-gradient(180deg,#000d1a,#00060d)', accentColor:'#38bdf8', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:12, name:'SOUL SOCIETY',      universe:'Bleach',                       arc:'Arc Arrancar',                subtitle:'La société des âmes en guerre',          bgGradient:'linear-gradient(180deg,#0a0000,#050000)', accentColor:'#f87171', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:13, name:'HOLY GRAIL WAR',    universe:'Fate',                         arc:'Unlimited Blade Works',       subtitle:'Sept Servants, un Graal',               bgGradient:'linear-gradient(180deg,#0a0814,#05040a)', accentColor:'#a78bfa', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:14, name:'TWILIGHT REALM',    universe:'The Legend of Zelda',          arc:'Twilight Princess',           subtitle:'Le royaume du crépuscule',              bgGradient:'linear-gradient(180deg,#0a0a00,#060600)', accentColor:'#fbbf24', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:15, name:'REPO HOUSE',        universe:'R.E.P.O',                      arc:'The Collection',              subtitle:'Récupérez les objets... si vous pouvez', bgGradient:'linear-gradient(180deg,#080814,#04040a)', accentColor:'#818cf8', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:16, name:"HOPE'S PEAK",       universe:'Danganronpa',                  arc:'Killing Game',                subtitle:'Désespoir contre Espoir',               bgGradient:'linear-gradient(180deg,#1a0014,#0d000a)', accentColor:'#e879f9', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:17, name:'THE BIG TOP',       universe:'Digital Circus',               arc:'Saison 1',                    subtitle:'Bienvenue dans le cirque numérique',    bgGradient:'linear-gradient(180deg,#00001a,#00000d)', accentColor:'#c084fc', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:18, name:'AINCRAD',           universe:'Sword Art Online',             arc:'Alicization',                 subtitle:'La mort dans le jeu est réelle',        bgGradient:'linear-gradient(180deg,#001414,#000a0a)', accentColor:'#67e8f9', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:19, name:'YOKOHAMA',          universe:'Bungou Stray Dogs',            arc:'Arc Port Mafia',              subtitle:'Détective vs Mafia vs Guilde',          bgGradient:'linear-gradient(180deg,#14000a,#0a0005)', accentColor:'#f472b6', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:20, name:"KING'S ROW",        universe:'Overwatch',                    arc:'La Guerre des Omniums',       subtitle:'Les héros ne meurent jamais',           bgGradient:'linear-gradient(180deg,#00000a,#000005)', accentColor:'#fb923c', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:21, name:'PAVILLON DE JADE',  universe:"Les Carnets de l'Apothicaire",arc:'Le Pavillon de Jade',         subtitle:'Intrigues à la cour impériale',         bgGradient:'linear-gradient(180deg,#1a1200,#0d0900)', accentColor:'#fde68a', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:22, name:'SEC. PUBLIQUE',     universe:'Chainsaw Man',                 arc:'Secteur de la Sécurité',      subtitle:'Chasse aux démons — Tokyo',             bgGradient:'linear-gradient(180deg,#1a0000,#0d0000)', accentColor:'#f87171', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:23, name:'OP. STRIX',         universe:'Spy x Family',                 arc:'Opération Strix',             subtitle:'Mission : famille parfaite',            bgGradient:'linear-gradient(180deg,#1a0a14,#0d0509)', accentColor:'#f472b6', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:24, name:'ARC NAMEK',         universe:'Dragon Ball',                  arc:'Arc Namek',                   subtitle:'Le conflit sur Namek',                  bgGradient:'linear-gradient(180deg,#001a0a,#000d05)', accentColor:'#34d399', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:25, name:'INFINITE CASTLE',   universe:'Demon Slayer',                 arc:'Infinite Castle',             subtitle:'Le château infini de Muzan',            bgGradient:'linear-gradient(180deg,#0a0014,#050009)', accentColor:'#c084fc', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:26, name:'GREAT CATACLYSM',   universe:'Fire Force',                   arc:'The Great Cataclysm',         subtitle:'Le monde en flammes',                   bgGradient:'linear-gradient(180deg,#1a0500,#0d0200)', accentColor:'#fb923c', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:27, name:'AMESTRIS',          universe:'Fullmetal Alchemist',          arc:'Brotherhood',                 subtitle:"La philosophie de la pierre",           bgGradient:'linear-gradient(180deg,#1a1400,#0d0a00)', accentColor:'#fbbf24', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:28, name:"LA FAILLE",         universe:'League of Legends',            arc:"La Faille de l'Invocateur",   subtitle:'La Faille ne pardonne pas',             bgGradient:'linear-gradient(180deg,#000a1a,#00050d)', accentColor:'#60a5fa', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:29, name:'ALABASTA',          universe:'One Piece',                    arc:'Alabasta',                    subtitle:'Le désert et le secret du Baroque Works',bgGradient:'linear-gradient(180deg,#1a1200,#0d0900)', accentColor:'#fde68a', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:30, name:'ROYAUME DES ANIMAUX',universe:'Nos Animaux',                arc:'Le Royaume',                  subtitle:'Les gardiens du royaume',               bgGradient:'linear-gradient(180deg,#001a14,#000d09)', accentColor:'#4ade80', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:31, name:'RAGNARÖK',          universe:'Valkyrie Apocalypse',          arc:'Le Royaume des Dieux',        subtitle:'Humains contre Dieux',                  bgGradient:'linear-gradient(180deg,#0a0014,#05000a)', accentColor:'#a78bfa', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:32, name:'HALLOWNEST',        universe:'Hollow Knight',                arc:"Le Royaume d'Hallownest",     subtitle:'Les profondeurs du royaume oublié',     bgGradient:'linear-gradient(180deg,#000a14,#00050a)', accentColor:'#38bdf8', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:33, name:"L'ÎLE DE PARADIS",  universe:'Attaque des Titans',           arc:"L'Île de Paradis",            subtitle:'Les Titans en marche',                  bgGradient:'linear-gradient(180deg,#0a0a0a,#050505)', accentColor:'#9ca3af', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:34, name:'PAYS DES DÉLICES',  universe:'Cuphead',                      arc:'Le Pays des Délices',         subtitle:'Une dette envers le Diable',            bgGradient:'linear-gradient(180deg,#1a0a00,#0d0500)', accentColor:'#fb923c', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:35, name:'LE SAINT GRAAL II', universe:'Fate',                         arc:'Le Saint Graal',              subtitle:'Une nouvelle guerre commence',          bgGradient:'linear-gradient(180deg,#1a0814,#0d040a)', accentColor:'#e879f9', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:36, name:"FAZBEAR'S PIZZA",   universe:"Five Nights At Freddy's",      arc:"Freddy's Fazbear Pizza",      subtitle:'Ne les laisse pas entrer',              bgGradient:'linear-gradient(180deg,#0a0500,#050200)', accentColor:'#fbbf24', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:37, name:'TOURNOI DU ROI',    universe:'Tekken',                       arc:'Le Tournoi du Roi du Poing',  subtitle:'Le sang Mishima coule',                 bgGradient:'linear-gradient(180deg,#1a0000,#0d0000)', accentColor:'#f87171', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:38, name:'MONDE SOUTERRAIN',  universe:'Undertale',                    arc:'Le Monde Souterrain',         subtitle:'Determination.',                        bgGradient:'linear-gradient(180deg,#00081a,#00040d)', accentColor:'#60a5fa', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:39, name:'RÉGION DE JOHTO',   universe:'Pokémon',                      arc:'Johto',                       subtitle:'Un nouveau voyage commence',            bgGradient:'linear-gradient(180deg,#1a0a00,#0d0500)', accentColor:'#fb923c', bossTimerSeconds:90,  monstersPerPalier:10 },
  { id:40, name:"L'ENTRE-TERRE",     universe:'Elden Ring',                   arc:"Le Royaume de l'Entre-Terre", subtitle:'Que la grâce guide tes pas',            bgGradient:'linear-gradient(180deg,#0a0a00,#050500)', accentColor:'#fde68a', bossTimerSeconds:90,  monstersPerPalier:10 },
];

// Au-delà du dernier palier défini, on cycle sur les mondes précédents (le
// thème/décor se répète) — seules les STATS des mobs continuent de monter
// avec le vrai palier (voir generateEnemy dans lib/game/enemies.ts).
export function getPalierConfig(p: number): PalierConfig {
  const cycled = ((p - 1) % PALIERS.length) + 1;
  return PALIERS[cycled - 1];
}
